name: mms_ptl
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - pip
  - altair=4.1.0
  - python-dateutil
  - nodejs
  - jupyterlab
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets
  - markdown
