#!/bin/bash

echo "Adding extensions"
#jupyter labextension install @jupyterlab/vega5-extension@2.1.0
jupyter labextension install jupyter-offlinenotebook
jupyter labextension install widgetsnbextension
jupyter labextension enable  widgetsnbextension 
jupyter labextension enable jupyter-offlinenotebook
